version: "3.9"

services:
  app:
    build: .
    container_name: smart_hr_bot_app
    restart: always
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - smart_hr_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "registry-1.docker.io:3.88.79.16"   # one of the IPv4 addresses from nslookup
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

networks:
  smart_hr_network:
    driver: bridge
